ID_UNCONNECTED_PING = 0x01
ID_UNCONNECTED_PING_OPEN_CONNECTIONS = 0x02
ID_OPEN_CONNECTION_REQUEST_1 = 0x05
ID_OPEN_CONNECTION_REPLY_1 = 0x06
ID_OPEN_CONNECTION_REQUEST_2 = 0x07
ID_OPEN_CONNECTION_REPLY_2 = 0x08
ID_CONNECTION_REQUEST = 0x09
ID_CONNECTION_REQUEST_ACCEPTED = 0x10
ID_CONNECTION_ATTEMPT_FAILED = 0x11
ID_ALREADY_CONNECTED = 0x12
ID_NEW_INCOMING_CONNECTION = 0x13
ID_NO_FREE_INCOMING_CONNECTIONS = 0x14
ID_DISCONNECTION_NOTIFICATION = 0x15
ID_CONNECTION_BANNED = 0x17
ID_INVALID_PASSWORD = 0x18
ID_INCOMPATIBLE_PROTOCOL_VERSION = 0x19
ID_IP_RECENTLY_CONNECTED = 0x1A
ID_UNCONNECTED_PONG = 0x1C

OFFLINE_MESSAGE_DATA_ID = b"\x00\xff\xff\x00\xfe\xfe\xfe\xfe\xfd\xfd\xfd\xfd\x12\x34\x56\x78"

RAKNET_PROTOCOL_VERSION = 11
UDP_HEADER_SIZE = 28
MAXIMUM_MTU_SIZE = 1400
NUMBER_OF_ORDERED_STREAMS = 32
MAXIMUM_NUMBER_OF_INTERNAL_IDS = 20
